project:
  # All paths are relative to the repository root by default
  gbif_dir: "data/amsterdam_2/train"
  image_dir: "data/amsterdam_2/images_no_vespula2"
  model_dir: "data/amsterdam_2/models_new"
